# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import masteradmin_pb2 as masteradmin__pb2


class MasterAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/gsdk.masteradmin.MasterAdmin/Get',
                request_serializer=masteradmin__pb2.GetRequest.SerializeToString,
                response_deserializer=masteradmin__pb2.GetResponse.FromString,
                )
        self.Set = channel.unary_unary(
                '/gsdk.masteradmin.MasterAdmin/Set',
                request_serializer=masteradmin__pb2.SetRequest.SerializeToString,
                response_deserializer=masteradmin__pb2.SetResponse.FromString,
                )
        self.SetMulti = channel.unary_unary(
                '/gsdk.masteradmin.MasterAdmin/SetMulti',
                request_serializer=masteradmin__pb2.SetMultiRequest.SerializeToString,
                response_deserializer=masteradmin__pb2.SetMultiResponse.FromString,
                )


class MasterAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMulti(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=masteradmin__pb2.GetRequest.FromString,
                    response_serializer=masteradmin__pb2.GetResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=masteradmin__pb2.SetRequest.FromString,
                    response_serializer=masteradmin__pb2.SetResponse.SerializeToString,
            ),
            'SetMulti': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMulti,
                    request_deserializer=masteradmin__pb2.SetMultiRequest.FromString,
                    response_serializer=masteradmin__pb2.SetMultiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gsdk.masteradmin.MasterAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gsdk.masteradmin.MasterAdmin/Get',
            masteradmin__pb2.GetRequest.SerializeToString,
            masteradmin__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gsdk.masteradmin.MasterAdmin/Set',
            masteradmin__pb2.SetRequest.SerializeToString,
            masteradmin__pb2.SetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMulti(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gsdk.masteradmin.MasterAdmin/SetMulti',
            masteradmin__pb2.SetMultiRequest.SerializeToString,
            masteradmin__pb2.SetMultiResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
