# Generated by Django 5.2.12 on 2026-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='ipfs_cid',
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_block_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('submitted', 'Submitted to Blockchain'), ('confirmed', 'Confirmed on Blockchain'), ('failed', 'Failed')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_blockchain_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='blockchain_network',
            field=models.CharField(blank=True, default='sepolia', max_length=20, null=True),
        ),
    ]
