# Generated by Django 5.2.12 on 2026-05-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contract_ipfs_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
