# Generated by Django 5.2.12 on 2026-04-30 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embedding', models.BinaryField(blank=True, help_text='Face embedding vector (encrypted)', null=True)),
                ('voice_embedding', models.BinaryField(blank=True, help_text='Voice embedding vector (encrypted)', null=True)),
                ('signature_template', models.TextField(blank=True, help_text='Signature template (encrypted)', null=True)),
                ('fingerprint_template', models.TextField(blank=True, help_text='Fingerprint template (encrypted)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Profile',
                'verbose_name_plural': 'Biometric Profiles',
                'db_table': 'biometric_profiles',
                'indexes': [models.Index(fields=['user', 'is_active'], name='biometric_p_user_id_73417e_idx'), models.Index(fields=['last_verified_at'], name='biometric_p_last_ve_7386dc_idx')],
            },
        ),
    ]
